name: CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet-version: [ '4.8.x' ]

    steps:
      - uses: actions/checkout@v3
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build the Solution
        run: msbuild Archon.SwissArmyLib.sln
